### ISSUE TITLE
Configurar integração com Travis

### ISSUE THREAD

**Issue by zdsantos** [TPII20152/BankSys05#1]
- [x] 1. Adicionar o repositório no Travis
- [x] 2. Criar os arquivos .travis.yml e build.xml

**Comment by zdsantos** [comment]
Tenho que esperar algum teste ser feito para terminar.
@thiagoisaias @karenraiany

**Comment by thiagoisaias** [comment]
Tenta aí.
@zdsantos

**Comment by zdsantos** [comment]
Fechado com o commit e1a98b152ff0eb14323e106d6e4c8b87c9324758
