### ISSUE TITLE
Implementar o log da operações

### ISSUE THREAD

**Issue by zdsantos** [TPII20152/BankSys05#3]
Implementar um log persistente de operações bancárias. Esse log deve registrar todas as operações  bancárias (operações de debito, credito, bônus, juros, transferência, cadastro e remoção de contas) em um arquivo de log ou em um banco de dados.

**Comment by thiagoisaias** [comment]
Eu nao usei o log4j ou logBack. Preferi fazer uma classe simples.
E acabei bagunçando o Controller ao invés de escrever tudo na Logger.
Tem algum problema? @zdsantos @lincolnrocha
