### ISSUE TITLE
Criar testes do pacote banksys.account

### ISSUE THREAD

**Issue by zdsantos** [TPII20152/BankSys05#5]
Implementar as classes de teste unitário para cada classe contida no pacote.

**Comment by thiagoisaias** [comment]
Ainda preciso adicionar alguns casos de teste importantes.
:+1:

**Comment by thiagoisaias** [comment]
Dei merge na master pro @zdsantos tentar fazer a integração.
Não vou fechar a issue pq os testes com as exceçōes ainda nao estao certos.
