### ISSUE TITLE
Não é possível criar novas contas

### ISSUE THREAD

**Issue by thiagoisaias** [TPII20152/BankSys05#8]
Por algum motivo não é possível criar uma conta nova. (Não importa o tipo da conta)

_Error: Transaction not perfermed!
Cause: OrdinaryAccount alredy exist!_
Acho q é uma exceçao do pacote persistence.

Da uma olhada la, @zdsantos 

<img width="575" alt="screen shot 2016-01-25 at 22 17 08" src="https://cloud.githubusercontent.com/assets/5006865/12569831/311d16e4-c3b1-11e5-9a54-2fca447c8caf.png">

**Comment by zdsantos** [comment]
Resolvido com o commit 9b95fdebc0e6787635c5a4e60519e89e7a7df8ce
